version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: file:./dev.db
    # Mount local sqlite DB and prisma schema so data persists and migrations run against the same files
    volumes:
      - ./dev.db:/app/dev.db
      - ./prisma:/app/prisma
    # Apply migrations (if any) and start the built app
    command: sh -c "npx prisma migrate deploy --schema=./prisma/schema.prisma || true && node dist/main"