version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin.
      POSTGRES_DB: backend_db
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://admin:admin.@db:5432/backend_db
    depends_on:
      - db